### ISSUE TITLE
Reverse proxy - empty context (missing trailing slash) results in wrong redirect

### ISSUE THREAD

**Issue by joachimnielandt** [INSPIRE-MIF/helpdesk-validator#936]
Hello everyone,

I am deploying version 2023.0 to a Kubernetes environment. The Inspire Validator now runs behind a Traefik reverse proxy. As configured, I have an external url (https://external/inspirevalidator) that redirects to the internal service (http://internal/validator:8090) through a path rewrite (in traefik). This works fine, except:
- https://external/inspirevalidator/ is fine
- https://external/inspirevalidator will fail - a redirect is triggered

My current understanding is that the spring boot application gets an empty context (no slash or path) and builds an absolute path (hostname + port + path) to perform a redirect. This absolute path fails:
- when unconfigured, the hostname is the internal pod name
- when passing the hostname as a header, this results in a redirect to https://external:8090, which includes the port so that fails as well

My question is: can I configure the docker container to have the empty context redirect to a relative `/`, instead? Or is this perhaps not the actual issue? Is there a 'proper' way of avoiding this problem and configuring the docker container to have a non-trailing-slash redirect?

**Comment by fernandocuevasgdtel** [comment]
Dear @joachimnielandt,

thank you for reporting the issue.
We have analyzed it and it seems that it could be a problem with the etf-config properties, maybe the url set includes a final slash, could you check?
We will conduct further testing so we can provide you with more feedback from our side, but it would be appreciated if you could provide us with any additional information.

Best regards,

**Comment by joachimnielandt** [comment]
Dear @fernandocuevasgdtel ,

Could you tell me how to modify / check the etf-config properties in a docker setup? Is that a file in the container itself, can it be modified through environment variables?

I have replicated a minimal working example in docker-compose (see below). This illustrates the problem, although the path rewrite is not a correct solution as the container itself will build URL's, based on an incorrect hostname, anyway (example: when running 'test results' in the UI, an http request is launched to `localhost:8090`, which would be incorrect in this setup).

When running the below docker-compose, the following is available:
- http://inspirevalidator.localhost/validator
- http://inspirevalidator2.localhost/inspirevalidator/

```yaml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  inspirevalidator:
    image: "docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2023.1"
    container_name: "inspire-validator"
    labels:
      - "traefik.enable=true"
      # this results in http://inspirevalidator.localhost/validator redirecting to http://inspirevalidator.localhost:8090/validator/
      - "traefik.http.routers.inspirevalidator.rule=Host(`inspirevalidator.localhost`)"
      - "traefik.http.routers.inspirevalidator.entrypoints=web"
      - "traefik.http.services.inspirevalidator.loadbalancer.server.port=8090"
  
  inspirevalidator2:
    image: "docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2023.1"
    container_name: "inspire-validator2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inspirevalidator2.rule=Host(`inspirevalidator2.localhost`)"
      # http://inspirevalidator2.localhost/inspirevalidator/ redirects properly, without trailing slash it doesn't
      - "traefik.http.middlewares.test-replacepathregex.replacepathregex.regex=^/inspirevalidator/?(.*)"
      - "traefik.http.middlewares.test-replacepathregex.replacepathregex.replacement=/validator/$$1"
      - "traefik.http.routers.inspirevalidator2.entrypoints=web"
      - "traefik.http.routers.inspirevalidator2.middlewares=test-replacepathregex@docker"
      - "traefik.http.services.inspirevalidator2.loadbalancer.server.port=8090"
```
